name=DFRobot_SGX6410_Gravity
version=1.0.0
author=DFRobot
maintainer=DFRobot <li.jia@dfrobot.com>
sentence=Read air quality data from the Gravity MEMS AQI Sensor SGX6410.(SKU: SEN0771)
paragraph=This library provides I2C and UART (Modbus RTU) interfaces to the Gravity SGX6410 module: IAQ, TVOC, ETOH, eCO2, RelIAQ, and humidity compensation.
category=Sensors
url=https://github.com/DFRobot/DFRobot_SGX6410_Gravity
architectures=*
depends=DFRobot_RTU
